### ISSUE TITLE
Bad link referencing tsconfig.json options

### ISSUE THREAD

**Issue by micahblu** [Microsoft/TypeScript-Handbook#565] opened 2017-04-25 00:24 UTC
In the page at `https://www.typescriptlang.org/docs/handbook/react-&-webpack.html` there is a line: `You can learn more about tsconfig.json files here.` where `here` links to a bad url `https://www.typescriptlang.org/tsconfig-json.html`. I believe the new url should be: `https://www.typescriptlang.org/docs/handbook/tsconfig-json.html`

Within this repo at `pages/tutorials/React & Webpack.md` The reference for `tsconfig.json` is relative but it doesn't appear that the actual website follows the same directory structure as the repo.

I'm not sure that replacing line 112: 
`You can learn more about `tsconfig.json` files [here](../../tsconfig.json.md).`
With:
`You can learn more about `tsconfig.json` files [here](../../docs/handbook/tsconfig.json.md).`
Would fix the issue?

**Comment by mhegazy** [comment] 2018-01-31 19:05
Duplicate of https://github.com/Microsoft/TypeScript-Handbook/issues/431 fixed by https://github.com/Microsoft/TypeScript-Handbook/pull/474

**Closed by mhegazy** 2018-01-31 19:05 UTC
