### ISSUE TITLE
Document `ThisType<T>`

### ISSUE THREAD

**Issue by trusktr** [microsoft/TypeScript-Handbook#1037] opened 2019-05-14 20:49 UTC
Continuing from https://github.com/microsoft/TypeScript-Handbook/issues/649, there doesn't seem to be a link to the "Utility Types" page in the sidebar menu, so it is hidden.

**Comment by Retsam** [comment] 2019-05-30 14:19
Yup, there's already #994 tracking this.

**Comment by karlhorky** [comment] 2019-07-03 15:16
@trusktr I think this can be closed, can't it? Since it's a dupe of #994?

**Comment by orta** [comment] 2019-07-03 16:00
Yep @karlhorky  just sent the fix and it's being deployed now

**Closed by orta** 2019-07-03 16:00 UTC
