### ISSUE TITLE
Missing word in Variable Declarations.md

### ISSUE THREAD

**Issue by drmacm** [Microsoft/TypeScript-Handbook#252] opened 2016-04-18 07:33 UTC
In the section "Block-scoped variable capturing", first paragraph has a missing word (I suppose it's the word "variables"):

> When we first touched on the idea of variable capturing with var declaration, we briefly went into how variables act once captured. To give a better intuition of this, each time a scope is run, it creates an "environment" of variables. That environment and its ????????? can exist even after everything within its scope has finished executing.

**Comment by mhegazy** [comment] 2016-04-18 19:55
looks like a duplicate of https://github.com/Microsoft/TypeScript-Handbook/issues/245

**Comment by mhegazy** [comment] 2016-04-18 19:55
PRs welcomed regardless.

**Closed by mhegazy** 2016-04-18 19:55 UTC
