### ISSUE TITLE
Clarify "Extending interfaces"

### ISSUE THREAD

**Issue by dirkpostma** [Microsoft/TypeScript-Handbook#149] opened 2016-02-13 15:06 UTC
In https://github.com/Microsoft/TypeScript-Handbook/blob/master/pages/Interfaces.md#extending-interfaces

The following syntax is used:

```
let square = <Square>{};
```

This is the first time the <    > notation is used. I don't know what this is yet, so I don't have a usggestion to improve, except for saying: this should either be explained, or the example should be rewritten without this syntax.

**Comment by DanielRosenwasser** [comment] 2016-02-14 08:49
That's a type assertion. It's a way of telling TypeScript that you should treat the `{}` with the `Square` type.

Also, duplicate of #123

**Closed by DanielRosenwasser** 2016-02-14 08:49 UTC
