### ISSUE TITLE
Repetition of content on live website

### ISSUE THREAD

**Issue by Swap76** [microsoft/TypeScript-Handbook#1044] opened 2019-05-30 20:05 UTC
![tsconfig](https://user-images.githubusercontent.com/37082605/58660898-2697ad00-8344-11e9-8f04-3abe1589abfb.png)

Name tsconfig.json is repeated on live website

**Comment by Rajatsoni9** [comment] 2019-06-03 05:48
Duplicate of #1011

**Comment by orta** [comment] 2019-07-03 16:01
This looks fixed now on my staging site 👍

**Closed by orta** 2019-07-03 16:01 UTC
