### ISSUE TITLE
The website handbook pages aren't available in mobile browsers

### ISSUE THREAD

**Issue by finian** [Microsoft/TypeScript-Handbook#260] opened 2016-04-26 17:05 UTC
When viewing docs pages (http://www.typescriptlang.org/docs/tutorial.html) in mobile browsers, the left nav panel is gone, just can't find any way to view the handbook pages.

**Comment by mhegazy** [comment] 2016-04-26 19:35
looks like a duplicate of https://github.com/Microsoft/TypeScript/issues/8119

**Closed by mhegazy** 2016-04-26 19:35 UTC

**Comment by mhegazy** [comment] 2016-04-26 19:45
should be fixed now, can you give http://www.typescriptlang.org/docs/tutorial.html another try.

**Comment by finian** [comment] 2016-04-27 01:44
cool. tnx.
