### ISSUE TITLE
Broken link on react-&-webpack.html

### ISSUE THREAD

**Issue by maakep** [Microsoft/TypeScript-Handbook#601] opened 2017-06-08 20:46 UTC
I read you were open sourcing the website but until then I suppose you'll have to correct this yourselves! :grin: 

https://www.typescriptlang.org/docs/handbook/react-&-webpack.html

>You can learn more about `tsconfig.json` files [here](https://www.typescriptlang.org/docs/tsconfig-json.html).

**Expected behavior:**
The link links to https://www.typescriptlang.org/docs/Handbook/tsconfig-json.html

**Actual behavior:**
It liks to https://www.typescriptlang.org/docs/tsconfig-json.html which is a broken link

**Comment by maakep** [comment] 2017-08-10 14:53
Still an issue as of 2017-08-10

**Comment by damiencaselli** [comment] 2017-10-26 16:51
@maakep I think it can be fixed by using a `./` link, but then it won't be linked properly when browsing the repository files. Since it is supposed to work either ways, I think this can't be resolved using the current directory structure.

**Comment by Niladri24dutta** [comment] 2017-12-05 18:11
Yes i checked from github that it points to the correct file but in the website I am not sure how the directory structure is maintained

**Comment by mhegazy** [comment] 2018-01-31 19:05
Duplicate of https://github.com/Microsoft/TypeScript-Handbook/issues/431 fixed by https://github.com/Microsoft/TypeScript-Handbook/pull/474

**Closed by mhegazy** 2018-01-31 19:05 UTC
