### ISSUE TITLE
Triple Slash <reference types="..." />

### ISSUE THREAD

**Issue by phreed** [Microsoft/TypeScript-Handbook#422] opened 2016-10-20 22:15 UTC
Apparently there is a new attribute `types` associated with the triple slash reference.
[It is mentioned here.](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#im-writing-a-definition-that-depends-on-another-definition-should-i-use-reference-types--or-an-import)

Some things that should be covered:
* when it is appropriate to use
* how it compares to `<reference path="..." />`
* the reason it was introduced

[I would expect the documentation to be here.](https://github.com/Microsoft/TypeScript-Handbook/blob/master/pages/Triple-Slash%20Directives.md)

**Comment by mhegazy** [comment] 2016-10-21 05:44
Duplicate of https://github.com/Microsoft/TypeScript-Handbook/issues/348

**Closed by mhegazy** 2016-10-21 05:44 UTC
